package com.hanif.medical.utils

object Routes {
    const val ROUTE_PRE_ADD_MANUAL_SCREEN = "ROUTE_PRE_ADD_MANUAL_SCREEN"
    const val ROUTE_ADD_EDIT_SCREEN = "ROUTE_ADD_EDIT"
    const val EDIT_PROFILE_SCREEN = "EDIT_PROFILE_SCREEN"
    const val REPORT_SCREEN = "REPORT_SCREEN"
    const val DETAIL_DOCTOR_SCREEN = "DETAIL_DOCTOR_SCREEN"
    const val SHOPPING_SCREEN = "SHOPPING_SCREEN"
    const val SHOPPING_ADDRESS_SCREEN = "SHOPPING_ADDRESS_SCREEN"
    const val SHOPPING_PRE_PAYMENT_SCREEN = "SHOPPING_PRE_PAYMENT_SCREEN"
    const val SHOPPING_DETAIL_SCREEN = "SHOPPING_DETAIL_SCREEN"
    const val SHOPPING_SUCCESSFUL_SCREEN = "SHOPPING_SUCCESSFUL_SCREEN"
    const val SHOPPING_CARD_PAYMENT_SCREEN = "SHOPPING_CARD_PAYMENT_SCREEN"
    const val ALL_DOCTOR_SCREEN = "APPOINTMENT_SCREEN"
    const val DOCTOR_BOOKING_PROCESS_FIRST_SCREEN = "DOCTOR_BOOKING_PROCESS_FIRST_SCREEN"
    const val DOCTOR_BOOKING_PROCESS_SECOND_SCREEN = "DOCTOR_BOOKING_PROCESS_SECOND_SCREEN"
    const val DOCTOR_BOOKING_PROCESS_THIRD_SCREEN = "DOCTOR_BOOKING_PROCESS_THIRD_SCREEN"
    const val ADD_CARD_SCREEN = "ADD_CARD_SCREEN"
    const val CONFORM_DOCTOR_APPOINTMENT = "CONFORM_DOCTOR_APPOINTMENT"
}
